# https://taskfile.dev

version: "3"

vars:
  targetbin: ~/bin
  buildname: pathhelper
  dir: >
    {{.DIR}}
  LDFLAGS: >
    -X 'main.GitCommit=$GIT_COMMIT'
    -X 'main.CompilationDate=$COMPILATION_DATE'
    -X 'main.CommitDate=$COMMIT_DATE'
env:
  GIT_COMMIT:
    sh: git rev-parse --short HEAD
  COMPILATION_DATE:
    sh: date "+%Y-%m-%d %H:%M:%S %z"
  COMMIT_DATE:
    sh: git log -1 --format="%ci"

tasks:
  default:
    cmds:
      - echo "use 'task -l' to list tasks"
    silent: true
  install:
    desc: copy build file to local bin
    dir: .
    preconditions:
      - test -d {{.targetbin}}/
    cmds:
      - task: build
      - cmd: rm {{.targetbin}}/{{.buildname}}
        ignore_error: true
      - cmd: cp ./build/{{.buildname}} {{.targetbin}}
        ignore_error: true
      - cmd: rm -f ./build/{{.buildname}}
        ignore_error: true
  build:
    desc: build app
    dir: cmd/{{.buildname}}
    cmds:
      - cmd: rm -f ../../build/{{.buildname}}
        ignore_error: true
      # - go build -ldflags="{{.LDFLAGS}}" -o ../../build/{{.buildname}} .
      - go build -o ../../build/{{.buildname}} .
  show-allocations:
    desc: show build optimizations
    dir: cmd/{{.buildname}}
    cmds:
      - cmd: go build -gcflags '-m -l' pathhelper.go 2>&1
  show-build:
    desc: show build optimizations
    dir: cmd/{{.buildname}}
    cmds:
      - cmd: go build -gcflags '-S -N' pathhelper.go 2>&1
